### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by ertay** [Adam--/MvxViewPager#1] opened 2015-05-04 14:08 UTC
Hey Adam,

When I try to run your project it throws an unhandled exception. Any ideas why this happens?

Cheers

Edit: Looks like a lot of stuff broke with the latest Xamarin 'stable' update heh.

**Comment by Adam--** [comment] 2015-05-04 21:36
Going down the path of incompatibility due to an update...

It works for me on Xamarin 3.9.302 and VS 2013 with the Nexus 4 4.4.2 player. I also updated Xamarin to 3.11.445 and ran it on a Nexus 5 with 5.1 and don't have any issues.

MvvmCross is 3.5.0
Android Support Libraryis 21.0.3.0
Material Pager Sliding Tab Strip is 1.0.1

**Comment by Adam--** [comment] 2015-05-05 19:36
I'm closing this issue since it is not reproducible.

**Closed by Adam--** 2015-05-05 19:36 UTC
